film-modal
Samokhvalova-Nata/filmoteka pull request #3
Opened 2023-04-14 09:40 UTC by NadiaOl

2023-04-14 10:19 UTC, Samokhvalova-Nata requested changes

2023-04-14 10:19 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +    font-family: 'Roboto';
font-family: 'Roboto'  і font-weight: 500 
можна не вказувати, вони задані для всього body в _common.scss, а там де font-weight має бути 400, там вказати.
Це не помилка, просто виходить дублювання. Спробуй вказати точково тільки де font-weight відрізняється від загального в body

2023-04-14 10:19 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +        @media screen and(min-width:1280px) {
Має бути 768px

2023-04-14 10:19 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +            gap: 4px;
По макету gap 8px з планшетної версії

2023-04-14 10:19 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +    height: 34;
px загубились

2023-04-14 10:19 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +    border: 1px solid black;
колір в HEX форматі #000000

2023-04-14 10:19 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +            height: 42;
px загубились

2023-04-14 10:19 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +}
Додати розмір кнопок для планшета
@media screen and(min-width:768px) {
            width: 137px;
            height: 38px;

2023-04-14 10:19 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +}
додати анімацію для ховера/фокуса
transition: background-color var(--transition);

2023-04-14 10:19 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +
додати анімацію для ховера/фокуса
transition: background-color var(--transition), color var(--transition), border-color var(--transition);

2023-04-14 17:35 UTC, NadiaOl commented on src/sass/components/_film-modal.scss
> +    height: 34;
ok

2023-04-14 17:38 UTC, NadiaOl commented on src/sass/components/_film-modal.scss
> +            gap: 4px;
ok

2023-04-14 17:38 UTC, NadiaOl commented on src/sass/components/_film-modal.scss
> +        @media screen and(min-width:1280px) {
ok

2023-04-14 17:40 UTC, NadiaOl commented on src/sass/components/_film-modal.scss
> +            height: 42;
ok

2023-04-14 17:45 UTC, NadiaOl commented on src/sass/components/_film-modal.scss
> +}
помилка в макеті - дві кнопки з проміжком між ними = 264, проміжок 8, тобто одна кнопка не може бути більше 128, тому залишила розміри що були для мобілки, та зміну розміра для десктопа

2023-04-14 17:54 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +}
Зрозуміло, добре

2023-04-14 18:05 UTC, NadiaOl commented on src/sass/components/_film-modal.scss
> +}
ok

2023-04-14 18:05 UTC, NadiaOl commented on src/sass/components/_film-modal.scss
> +
ok

2023-04-14 19:13 UTC, Samokhvalova-Nata requested changes

2023-04-14 19:13 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +}
Цей має бути в класі елемента, а не його ховері, тобто в:
.modal__close-button {
}

2023-04-14 19:13 UTC, Samokhvalova-Nata commented on src/sass/components/_film-modal.scss
> +    transition: background-color var(--transition);
Тут також transition має бути на класі елемента, а не в ховері, тобто в:
.modal__button-watched,
.modal__button-queue {
};
І крім background-color в transition мають бути color і border-color, бо так перехід спрацює тільки на background-color

2023-04-15 12:39 UTC, Samokhvalova-Nata approved these changes

2023-04-15 12:39 UTC, merged