Feature/api
Samokhvalova-Nata/filmoteka pull request #9
Opened 2023-04-15 10:06 UTC by lukovjr

2023-04-15 12:30 UTC, oshaleyko59 requested changes

2023-04-15 12:30 UTC, oshaleyko59 commented on src/js/API.js
на доопрацювання:
1)  ви експортуєте об'єкт - це не має сенсу, бо у вас в конструкторі нема параметрів(тобто об'єкт буде завжди однаковий). зручніше експортувати екземпляр
2) в класі нема можливості змінити сторінку - вона завжди перша
3) ваш метод fetchMovie повертає проміс ( а має повертати вже дані)
4) метод fetchMovie не працює взагалі  - повертає "API.js:24 Uncaught (in promise) Error: Request failed with status code 404
    at FetchThemoviedbAPI.fetchMovie (API.js:24:13)"
4) потрібно для проекту - а) повертати trending movies б) повертати по ключовому слову с) повертати детальну інформацію по movie id

2023-04-15 15:01 UTC, oshaleyko59 reviewed
1) для пагінації малувато інкремент і декремент сторінки - там є клік по конкретній. Потрбно зробити сеттер. Або просто передавати номер сторінки в параметрах функції і не зберігати його в класі зовсім - оце найкраще
2) пришліть скрипт яким ви тестували всі свої методи класу

2023-04-16 07:05 UTC, Samokhvalova-Nata approved these changes

2023-04-17 16:21 UTC, closed without merging